# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vision_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from slidebar_pop import *
from code_pop import *

class Ui_MainWindow(object):
    def code(self):
        self.windowc.show()
    def slide(self):
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 1000)


        #Slider Pop Up Block Start
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_PopWindow()
        self.ui.setupUi(self.window)
        #Slider Pop Up Block End


        #Code Pop Up Block Start
        self.windowc = QtWidgets.QMainWindow()
        self.uic=Ui_Code()
        self.uic.setupUi(self.windowc)
        #Code Pop Up Block End
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1171, 951))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 1126, 863))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.log_label = QtWidgets.QLabel(self.layoutWidget)
        self.log_label.setStyleSheet("")
        self.log_label.setObjectName("log_label")
        self.verticalLayout_7.addWidget(self.log_label)
        self.log_out = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.log_out.setAutoFillBackground(False)
        self.log_out.setStyleSheet("")
        self.log_out.setReadOnly(True)
        self.log_out.setPlainText("")
        self.log_out.setObjectName("log_out")
        self.verticalLayout_7.addWidget(self.log_out)
        self.verticalLayout_11.addLayout(self.verticalLayout_7)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.settings_label = QtWidgets.QLabel(self.layoutWidget)
        self.settings_label.setObjectName("settings_label")
        self.horizontalLayout_21.addWidget(self.settings_label)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_21.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_21.addWidget(self.comboBox)
        self.verticalLayout_11.addLayout(self.horizontalLayout_21)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.s_focus_label = QtWidgets.QLabel(self.groupBox)
        self.s_focus_label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.s_focus_label.setObjectName("s_focus_label")
        self.horizontalLayout.addWidget(self.s_focus_label)
        self.s_focus_auto_button = QtWidgets.QRadioButton(self.groupBox)
        self.s_focus_auto_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.s_focus_auto_button.setObjectName("s_focus_auto_button")
        self.horizontalLayout.addWidget(self.s_focus_auto_button)
        self.s_focus_default_button = QtWidgets.QRadioButton(self.groupBox)
        self.s_focus_default_button.setObjectName("s_focus_default_button")
        self.horizontalLayout.addWidget(self.s_focus_default_button)
        self.s_focus_slide_button = QtWidgets.QRadioButton(self.groupBox)
        self.s_focus_slide_button.setObjectName("s_focus_slide_button")
        self.horizontalLayout.addWidget(self.s_focus_slide_button)
        self.verticalLayout.addWidget(self.groupBox)
        self.exposureBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.exposureBox.setTitle("")
        self.exposureBox.setObjectName("exposureBox")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.exposureBox)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.s_exposure_label = QtWidgets.QLabel(self.exposureBox)
        self.s_exposure_label.setObjectName("s_exposure_label")
        self.horizontalLayout_10.addWidget(self.s_exposure_label)
        self.s_expose_auto_button = QtWidgets.QRadioButton(self.exposureBox)
        self.s_expose_auto_button.setObjectName("s_expose_auto_button")
        self.horizontalLayout_10.addWidget(self.s_expose_auto_button)
        self.s_expose_default_button = QtWidgets.QRadioButton(self.exposureBox)
        self.s_expose_default_button.setObjectName("s_expose_default_button")
        self.horizontalLayout_10.addWidget(self.s_expose_default_button)
        self.s_expose_slide_button = QtWidgets.QRadioButton(self.exposureBox)
        self.s_expose_slide_button.setObjectName("s_expose_slide_button")
        self.horizontalLayout_10.addWidget(self.s_expose_slide_button)
        self.verticalLayout.addWidget(self.exposureBox)
        self.verticalLayout_11.addLayout(self.verticalLayout)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.filter_label = QtWidgets.QLabel(self.layoutWidget)
        self.filter_label.setObjectName("filter_label")
        self.horizontalLayout_7.addWidget(self.filter_label)
        self.filter_options = QtWidgets.QComboBox(self.layoutWidget)
        self.filter_options.setObjectName("filter_options")
        self.horizontalLayout_7.addWidget(self.filter_options)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.verticalLayout_11.addLayout(self.verticalLayout_9)
        self.listWidget = QtWidgets.QListWidget(self.layoutWidget)
        self.listWidget.setMaximumSize(QtCore.QSize(10000, 100))
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_11.addWidget(self.listWidget)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.button_label = QtWidgets.QLabel(self.layoutWidget)
        self.button_label.setObjectName("button_label")
        self.verticalLayout_10.addWidget(self.button_label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.access_directory_button = QtWidgets.QPushButton(self.layoutWidget)
        self.access_directory_button.setObjectName("access_directory_button")
        self.horizontalLayout_3.addWidget(self.access_directory_button)
        self.screen_shot = QtWidgets.QPushButton(self.layoutWidget)
        self.screen_shot.setObjectName("screen_shot")
        self.horizontalLayout_3.addWidget(self.screen_shot)
        self.add_filter_settings = QtWidgets.QPushButton(self.layoutWidget)
        self.add_filter_settings.setObjectName("add_filter_settings")
        self.horizontalLayout_3.addWidget(self.add_filter_settings)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.video_out_label = QtWidgets.QLabel(self.layoutWidget)
        self.video_out_label.setMinimumSize(QtCore.QSize(91, 16))
        self.video_out_label.setObjectName("video_out_label")
        self.horizontalLayout_8.addWidget(self.video_out_label)
        self.video_input = QtWidgets.QComboBox(self.layoutWidget)
        self.video_input.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.video_input.setObjectName("video_input")
        self.horizontalLayout_8.addWidget(self.video_input)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        self.videoout = QtWidgets.QLabel(self.layoutWidget)
        self.videoout.setMinimumSize(QtCore.QSize(600, 600))
        self.videoout.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.videoout.setFrameShape(QtWidgets.QFrame.Box)
        self.videoout.setText("")
        self.videoout.setObjectName("videoout")
        self.verticalLayout_12.addWidget(self.videoout)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.time_label = QtWidgets.QLabel(self.layoutWidget)
        self.time_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.time_label.setFrameShape(QtWidgets.QFrame.Box)
        self.time_label.setMidLineWidth(0)
        self.time_label.setText("")
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.horizontalLayout_9.addWidget(self.time_label)
        self.verticalLayout_13.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.start_button = QtWidgets.QPushButton(self.layoutWidget)
        self.start_button.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout_6.addWidget(self.start_button)
        self.stop_button = QtWidgets.QPushButton(self.layoutWidget)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout_6.addWidget(self.stop_button)
        self.verticalLayout_13.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.carimg1 = QtWidgets.QLabel(self.layoutWidget)
        self.carimg1.setMinimumSize(QtCore.QSize(100, 100))
        self.carimg1.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.carimg1.setFrameShape(QtWidgets.QFrame.Box)
        self.carimg1.setText("")
        self.carimg1.setObjectName("carimg1")
        self.horizontalLayout_4.addWidget(self.carimg1)
        spacerItem = QtWidgets.QSpacerItem(66, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.carimg2 = QtWidgets.QLabel(self.layoutWidget)
        self.carimg2.setMinimumSize(QtCore.QSize(100, 100))
        self.carimg2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.carimg2.setFrameShape(QtWidgets.QFrame.Box)
        self.carimg2.setText("")
        self.carimg2.setObjectName("carimg2")
        self.horizontalLayout_4.addWidget(self.carimg2)
        spacerItem1 = QtWidgets.QSpacerItem(66, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.carimg3 = QtWidgets.QLabel(self.layoutWidget)
        self.carimg3.setMinimumSize(QtCore.QSize(100, 100))
        self.carimg3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.carimg3.setFrameShape(QtWidgets.QFrame.Box)
        self.carimg3.setText("")
        self.carimg3.setObjectName("carimg3")
        self.horizontalLayout_4.addWidget(self.carimg3)
        spacerItem2 = QtWidgets.QSpacerItem(66, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.carimg4 = QtWidgets.QLabel(self.layoutWidget)
        self.carimg4.setMinimumSize(QtCore.QSize(100, 100))
        self.carimg4.setMaximumSize(QtCore.QSize(100, 100))
        self.carimg4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.carimg4.setFrameShape(QtWidgets.QFrame.Box)
        self.carimg4.setText("")
        self.carimg4.setObjectName("carimg4")
        self.horizontalLayout_4.addWidget(self.carimg4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_13)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 1126, 863))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.log_label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.log_label_2.setStyleSheet("")
        self.log_label_2.setObjectName("log_label_2")
        self.verticalLayout_15.addWidget(self.log_label_2)
        self.log_out_2 = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        self.log_out_2.setAutoFillBackground(False)
        self.log_out_2.setStyleSheet("")
        self.log_out_2.setReadOnly(True)
        self.log_out_2.setPlainText("")
        self.log_out_2.setObjectName("log_out_2")
        self.verticalLayout_15.addWidget(self.log_out_2)
        self.verticalLayout_14.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.settings_label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.settings_label_2.setObjectName("settings_label_2")
        self.verticalLayout_16.addWidget(self.settings_label_2)
        self.verticalLayout_14.addLayout(self.verticalLayout_16)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget_2)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.s_focus_label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.s_focus_label_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.s_focus_label_2.setObjectName("s_focus_label_2")
        self.horizontalLayout_12.addWidget(self.s_focus_label_2)
        self.s_focus_auto_button_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.s_focus_auto_button_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.s_focus_auto_button_2.setObjectName("s_focus_auto_button_2")
        self.horizontalLayout_12.addWidget(self.s_focus_auto_button_2)
        self.s_focus_default_button_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.s_focus_default_button_2.setObjectName("s_focus_default_button_2")
        self.horizontalLayout_12.addWidget(self.s_focus_default_button_2)
        self.s_focus_slide_button_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.s_focus_slide_button_2.setObjectName("s_focus_slide_button_2")
        self.horizontalLayout_12.addWidget(self.s_focus_slide_button_2)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.exposureBox_2 = QtWidgets.QGroupBox(self.layoutWidget_2)
        self.exposureBox_2.setTitle("")
        self.exposureBox_2.setObjectName("exposureBox_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.exposureBox_2)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.s_exposure_label_2 = QtWidgets.QLabel(self.exposureBox_2)
        self.s_exposure_label_2.setObjectName("s_exposure_label_2")
        self.horizontalLayout_13.addWidget(self.s_exposure_label_2)
        self.s_expose_auto_button_2 = QtWidgets.QRadioButton(self.exposureBox_2)
        self.s_expose_auto_button_2.setObjectName("s_expose_auto_button_2")
        self.horizontalLayout_13.addWidget(self.s_expose_auto_button_2)
        self.s_expose_default_button_2 = QtWidgets.QRadioButton(self.exposureBox_2)
        self.s_expose_default_button_2.setObjectName("s_expose_default_button_2")
        self.horizontalLayout_13.addWidget(self.s_expose_default_button_2)
        self.s_expose_slide_button_2 = QtWidgets.QRadioButton(self.exposureBox_2)
        self.s_expose_slide_button_2.setObjectName("s_expose_slide_button_2")
        self.horizontalLayout_13.addWidget(self.s_expose_slide_button_2)
        self.verticalLayout_2.addWidget(self.exposureBox_2)
        self.verticalLayout_14.addLayout(self.verticalLayout_2)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.filter_label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.filter_label_2.setObjectName("filter_label_2")
        self.horizontalLayout_15.addWidget(self.filter_label_2)
        self.filter_options_2 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.filter_options_2.setObjectName("filter_options_2")
        self.horizontalLayout_15.addWidget(self.filter_options_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14.addLayout(self.verticalLayout_6)
        self.verticalLayout_17.addLayout(self.horizontalLayout_14)
        self.verticalLayout_14.addLayout(self.verticalLayout_17)
        self.listWidget_2 = QtWidgets.QListWidget(self.layoutWidget_2)
        self.listWidget_2.setMaximumSize(QtCore.QSize(10000, 100))
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_14.addWidget(self.listWidget_2)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.button_label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.button_label_2.setObjectName("button_label_2")
        self.verticalLayout_18.addWidget(self.button_label_2)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.access_directory_button_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.access_directory_button_2.setObjectName("access_directory_button_2")
        self.horizontalLayout_16.addWidget(self.access_directory_button_2)
        self.screen_shot_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.screen_shot_2.setObjectName("screen_shot_2")
        self.horizontalLayout_16.addWidget(self.screen_shot_2)
        self.advanced_settings_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.advanced_settings_2.setObjectName("advanced_settings_2")
        self.horizontalLayout_16.addWidget(self.advanced_settings_2)
        self.verticalLayout_18.addLayout(self.horizontalLayout_16)
        self.verticalLayout_14.addLayout(self.verticalLayout_18)
        self.horizontalLayout_11.addLayout(self.verticalLayout_14)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.video_out_label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.video_out_label_2.setMinimumSize(QtCore.QSize(91, 16))
        self.video_out_label_2.setObjectName("video_out_label_2")
        self.horizontalLayout_17.addWidget(self.video_out_label_2)
        self.video_input_2 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.video_input_2.setObjectName("video_input_2")
        self.horizontalLayout_17.addWidget(self.video_input_2)
        self.verticalLayout_20.addLayout(self.horizontalLayout_17)
        self.videoout_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.videoout_2.setMinimumSize(QtCore.QSize(600, 600))
        self.videoout_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.videoout_2.setFrameShape(QtWidgets.QFrame.Box)
        self.videoout_2.setText("")
        self.videoout_2.setObjectName("videoout_2")
        self.verticalLayout_20.addWidget(self.videoout_2)
        self.verticalLayout_19.addLayout(self.verticalLayout_20)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.time_label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.time_label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.time_label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.time_label_2.setMidLineWidth(0)
        self.time_label_2.setText("")
        self.time_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label_2.setObjectName("time_label_2")
        self.horizontalLayout_18.addWidget(self.time_label_2)
        self.verticalLayout_19.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.start_button_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.start_button_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.start_button_2.setObjectName("start_button_2")
        self.horizontalLayout_19.addWidget(self.start_button_2)
        self.stop_button_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.stop_button_2.setObjectName("stop_button_2")
        self.horizontalLayout_19.addWidget(self.stop_button_2)
        self.verticalLayout_19.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.carimg1_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.carimg1_2.setMinimumSize(QtCore.QSize(100, 100))
        self.carimg1_2.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.carimg1_2.setFrameShape(QtWidgets.QFrame.Box)
        self.carimg1_2.setText("")
        self.carimg1_2.setObjectName("carimg1_2")
        self.horizontalLayout_20.addWidget(self.carimg1_2)
        spacerItem3 = QtWidgets.QSpacerItem(66, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem3)
        self.carimg2_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.carimg2_2.setMinimumSize(QtCore.QSize(100, 100))
        self.carimg2_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.carimg2_2.setFrameShape(QtWidgets.QFrame.Box)
        self.carimg2_2.setText("")
        self.carimg2_2.setObjectName("carimg2_2")
        self.horizontalLayout_20.addWidget(self.carimg2_2)
        spacerItem4 = QtWidgets.QSpacerItem(66, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem4)
        self.carimg3_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.carimg3_2.setMinimumSize(QtCore.QSize(100, 100))
        self.carimg3_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.carimg3_2.setFrameShape(QtWidgets.QFrame.Box)
        self.carimg3_2.setText("")
        self.carimg3_2.setObjectName("carimg3_2")
        self.horizontalLayout_20.addWidget(self.carimg3_2)
        spacerItem5 = QtWidgets.QSpacerItem(66, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem5)
        self.carimg4_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.carimg4_2.setMinimumSize(QtCore.QSize(100, 100))
        self.carimg4_2.setMaximumSize(QtCore.QSize(100, 100))
        self.carimg4_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.carimg4_2.setFrameShape(QtWidgets.QFrame.Box)
        self.carimg4_2.setText("")
        self.carimg4_2.setObjectName("carimg4_2")
        self.horizontalLayout_20.addWidget(self.carimg4_2)
        self.verticalLayout_19.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_11.addLayout(self.verticalLayout_19)
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.log_label.setText(_translate("MainWindow", "Log"))
        self.settings_label.setText(_translate("MainWindow", "Settings :"))
        self.label.setText(_translate("MainWindow", "Log Level:"))
        self.s_focus_label.setText(_translate("MainWindow", "Focus :"))
        self.s_focus_auto_button.setText(_translate("MainWindow", "Auto-Focus"))
        self.s_focus_default_button.setText(_translate("MainWindow", "Default Focus"))
        self.s_focus_slide_button.setText(_translate("MainWindow", "Focus Slidebar"))
        self.s_exposure_label.setText(_translate("MainWindow", "Exposure :"))
        self.s_expose_auto_button.setText(_translate("MainWindow", "Auto-Exposure"))
        self.s_expose_default_button.setText(_translate("MainWindow", "Default Expsoure"))
        self.s_expose_slide_button.setText(_translate("MainWindow", "Exposure Slidebar"))
        self.filter_label.setText(_translate("MainWindow", "Filters :"))
        self.button_label.setText(_translate("MainWindow", "Action buttons :"))
        self.access_directory_button.setText(_translate("MainWindow", "Access Directory"))
        self.screen_shot.setText(_translate("MainWindow", "Screen Shot"))
        self.add_filter_settings.setText(_translate("MainWindow", "Add Filter"))
        self.video_out_label.setText(_translate("MainWindow", "Video Stream"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Video 1"))
        self.log_label_2.setText(_translate("MainWindow", "Log"))
        self.settings_label_2.setText(_translate("MainWindow", "Settings :"))
        self.s_focus_label_2.setText(_translate("MainWindow", "Focus :"))
        self.s_focus_auto_button_2.setText(_translate("MainWindow", "Auto-Focus"))
        self.s_focus_default_button_2.setText(_translate("MainWindow", "Default Focus"))
        self.s_focus_slide_button_2.setText(_translate("MainWindow", "Focus Slidebar"))
        self.s_exposure_label_2.setText(_translate("MainWindow", "Exposure :"))
        self.s_expose_auto_button_2.setText(_translate("MainWindow", "Auto-Exposure"))
        self.s_expose_default_button_2.setText(_translate("MainWindow", "Default Expsoure"))
        self.s_expose_slide_button_2.setText(_translate("MainWindow", "Exposure Slidebar"))
        self.filter_label_2.setText(_translate("MainWindow", "Filters :"))
        self.button_label_2.setText(_translate("MainWindow", "Action buttons :"))
        self.access_directory_button_2.setText(_translate("MainWindow", "Access Directory"))
        self.screen_shot_2.setText(_translate("MainWindow", "Screen Shot"))
        self.advanced_settings_2.setText(_translate("MainWindow", "Advanced Settings"))
        self.video_out_label_2.setText(_translate("MainWindow", "Video Stream"))
        self.start_button_2.setText(_translate("MainWindow", "Start"))
        self.stop_button_2.setText(_translate("MainWindow", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Video 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

